"""Schemas package."""
from .flashcard import (
    GenerateRequest,
    GenerateResponse,
    GenerateResponseData,
    FlashcardObject,
    GenerateMetadata,
    ErrorDetail,
    HealthResponse,
)
from .auth import (
    RegisterRequest,
    LoginRequest,
    UserOut,
    AuthResponseData,
    AuthResponse,
)
from .deck import (
    APIError,
    DeckCreate,
    DeckUpdate,
    DeckOut,
    DeckResponse,
    DeckListResponse,
    CardCreate,
    CardUpdate,
    CardOut,
    CardResponse,
    CardListResponse,
)
from .review import (
    ReviewSessionCreate,
    ReviewSessionOut,
    ReviewAttemptCreate,
    ReviewAttemptOut,
    ReviewSessionResponse,
    ReviewSessionListResponse,
    ReviewAttemptResponse,
    ReviewAttemptListResponse,
)

__all__ = [
    "GenerateRequest",
    "GenerateResponse",
    "GenerateResponseData",
    "FlashcardObject",
    "GenerateMetadata",
    "ErrorDetail",
    "HealthResponse",
    "RegisterRequest",
    "LoginRequest",
    "UserOut",
    "AuthResponseData",
    "AuthResponse",
    "APIError",
    "DeckCreate",
    "DeckUpdate",
    "DeckOut",
    "DeckResponse",
    "DeckListResponse",
    "CardCreate",
    "CardUpdate",
    "CardOut",
    "CardResponse",
    "CardListResponse",
    "ReviewSessionCreate",
    "ReviewSessionOut",
    "ReviewAttemptCreate",
    "ReviewAttemptOut",
    "ReviewSessionResponse",
    "ReviewSessionListResponse",
    "ReviewAttemptResponse",
    "ReviewAttemptListResponse",
]
