"""add card classifications

Revision ID: 4aecbbd97834
Revises: a21d9ab1b6ff
Create Date: 2026-04-17 18:07:03.683594

"""
from alembic import op
import sqlalchemy as sa



revision = '4aecbbd97834'
down_revision = 'a21d9ab1b6ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('difficulty', sa.String(length=50), nullable=True))
    op.add_column('cards', sa.Column('question_type', sa.String(length=50), nullable=True))
    op.add_column('cards', sa.Column('topic', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'topic')
    op.drop_column('cards', 'question_type')
    op.drop_column('cards', 'difficulty')
    # ### end Alembic commands ###
